# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  cooldown:
    default-days: 30
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  labels:
  - dependencies
  cooldown:
    default-days: 30
