# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
      integration:
        flags:
        - integration
      unit:
        flags:
        - unit
    patch:
      default:
        target: auto
        threshold: 1%
      integration:
        flags:
        - integration
      unit:
        flags:
        - unit
flag_management:
  default_rules:
    carryforward: true
    paths:
    - internal/adapters/
    - internal/usecases/
    statuses:
    - type: project
      target: auto
      threshold: 1%
    - type: patch
      target: auto
      threshold: 1%
  individual_flags:
  - name: integration
  - name: unit
component_management:
  default_rules:
    statuses:
    - type: project
    - type: patch
  individual_components:
  - component_id: adapters
    name: adapters
    paths:
    - internal/adapters/**
  - component_id: usecases
    name: usecases
    paths:
    - internal/usecases/**
