# yaml-language-server: $schema=https://json.schemastore.org/codecov.json
coverage:
  status:
    project:
      default:
        target: auto
      integration:
        target: auto
        flags:
        - integration
      unit:
        target: auto
        flags:
        - unit
    patch:
      default:
        target: auto

flag_management:
  default_rules:
    carryforward: true
    statuses:
    - type: project
      target: auto
      threshold: 1%
    - type: patch
      target: 90%
  individual_flags:
  - name: integration
    paths:
    - internal/adapters/
    - internal/usecases/
  - name: unit
    paths:
    - internal/adapters/
    - internal/usecases/

component_management:
  default_rules:
    statuses:
    - type: project
    - type: patch
  individual_components:
  - component_id: adapters
    name: Adapters
    paths:
    - internal/adapters/**
  - component_id: usecases
    name: Use Cases
    paths:
    - internal/usecases/**
