# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: anilistarr
before:
  hooks:
  - ./.git/hooks/pre-commit
  - nix flake check -L
builds:
- id: handler
  main: ./cmd/handler
  binary: bin/handler
  flags:
  - -trimpath
  ldflags:
  - -s -w -X main.version={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: amd64
  - goos: darwin
    goarch: "386"
checksum:
  name_template: 'checksums.txt'
gomod:
  proxy: true
  mod: readonly
snapshot:
  version_template: "{{- .RawVersion -}}+{{ .FullCommit }}"
changelog:
  disable: true
release:
  github:
    owner: wwmoraes
    name: anilistarr
  prerelease: auto
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
