# yaml-language-server: $schema=https://github.com/wwmoraes/kaizen/raw/master/schemas/goreleaser.schema.json
project_name: anilistarr
before:
  hooks:
  - task check
builds:
- id: handler
  main: ./cmd/handler
  binary: bin/handler
  flags:
  - -race
  - -trimpath
  ldflags:
  - -s -w -X main.build={{.Version}}
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - "7"
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: "386"
checksum:
  name_template: 'checksums.txt'
gomod:
  proxy: true
  mod: readonly
snapshot:
  name_template: "{{- .Version -}}+{{ .FullCommit }}"
changelog:
  disable: true
release:
  github:
    owner: wwmoraes
    name: anilistarr
  prerelease: auto
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
