before:
  hooks:
  - go mod download
builds:
- id: handler
  main: ./cmd/handler
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm
  - arm64
  goarm:
  - 7
  ignore:
  - goos: darwin
    goarch: arm
  - goos: darwin
    goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-rc"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
release:
  github:
    owner: wwmoraes
    name: anilistarr
  prerelease: auto
