#:schema https://raw.githubusercontent.com/cocogitto/cocogitto/refs/heads/main/website/public/cog-schema.json

branch_whitelist = ["master"]
from_latest_tag = true
post_bump_hooks = [
  "git push",
  "git push {{version}}",
  "goreleaser release --clean --release-notes CHANGELOG.md",
]
pre_bump_hooks = [
  "goreleaser check",
  "goreleaser healthcheck",
  "make check",
]
tag_prefix = "v"

[git_hooks.commit-msg]
script = """#!/usr/bin/env sh
grep -q "^fixup! " "$1" || cog verify --file "$1"
git interpret-trailers --in-place --trailer signer --trailer patch-stack --trim-empty "$1"
"""

[git_hooks.post-checkout]
script = """make configure"""

[git_hooks.pre-commit]
script = """#!/usr/bin/env sh
set -eu

checkmake Makefile
hadolint Dockerfile
editorconfig-checker
markdownlint "**/*.md"
env -u GOFLAGS make generate
env -u GOFLAGS golangci-lint run
"""

[git_hooks.pre-push]
script = """#!/usr/bin/env sh
set -eu

nix flake check -L
env -u GOFLAGS make dist image
"""

[changelog]
authors = [{ signature = "William Artero", username = "wwmoraes" }]
owner = "wwmoraes"
package_template = "package_remote"
path = "CHANGELOG.md"
remote = "github.com"
repository = "anilistarr"
template = "remote"
