# fly.toml app configuration file generated for anilistarr on 2023-07-27T00:01:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anilistarr"
primary_region = "ams"

[env]
ANILIST_GRAPHQL_ENDPOINT = "https://graphql.anilist.co"
DATA_PATH = "/tmp"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[metrics]
port = 9091 # default for most prometheus clients
path = "/metrics" # default for most prometheus clients
