# fly.toml app configuration file generated for anilistarr on 2023-07-27T00:01:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "anilistarr"
primary_region = "ams"

[env]
ANILIST_GRAPHQL_ENDPOINT = "https://graphql.anilist.co"
DATA_PATH = "/var/tmp/handler"
OTEL_EXPORTER_OTLP_PROTOCOL = "http/protobuf"
OTEL_EXPORTER_OTLP_ENDPOINT = "https://otlp-gateway-prod-eu-west-0.grafana.net/otlp"
OTEL_RESOURCE_ATTRIBUTES = "deployment.environment=production"

[build.args]
VERSION = "0.1.0-rc.1"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[metrics]
port = 9091       # default for most prometheus clients
path = "/metrics" # default for most prometheus clients

[mounts]
auto_extend_size_limit = "5GB"
auto_extend_size_threshold = 80
destination = "/var/tmp/handler"
initial_size = "1GB"
snapshot_retention = 1
source = "handler"
