schema = 3

[mod]
  [mod."cel.dev/expr"]
    version = "v0.24.0"
    hash = "sha256-tg5zUJByc0QtiN3/dVxSH+6K7Bk/tLwzLBd7JjNs3iY="
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/Khan/genqlient"]
    version = "v0.8.1"
    hash = "sha256-6PYwpjpPN99oG+dRMhSgsNVLWTH8dNjqKUW2+jtYar0="
  [mod."github.com/XSAM/otelsql"]
    version = "v0.39.0"
    hash = "sha256-dNXBU6NIY5wrFk/iTPVfsky5o7dZdOfwPCJtItBhTnk="
  [mod."github.com/agiledragon/gomonkey/v2"]
    version = "v2.12.0"
    hash = "sha256-HtwjK/HCiwDA0/+1rS59aD0H9pvnf6E2JgBEpo7dnZY="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-3XnCzf7tFgEE0MmjxvjfWaw6qK6mKLabFZ3c23JIH9Y="
  [mod."github.com/alexflint/go-arg"]
    version = "v1.5.1"
    hash = "sha256-IaQwOGoVvcmq8CRj/lyOFJhlKepg/ICxAjbtJFBK6EY="
  [mod."github.com/alexflint/go-scalar"]
    version = "v1.2.0"
    hash = "sha256-PivG79qqrPJ1CksNiNNlwC+xPCMMTQxtda3rwk/z6LA="
  [mod."github.com/antlr4-go/antlr/v4"]
    version = "v4.13.1"
    hash = "sha256-beAuxHNRUuhzcSJUh/8ztVf1zCUiaT72fg2Jvx0AuNQ="
  [mod."github.com/bmatcuk/doublestar/v4"]
    version = "v4.8.1"
    hash = "sha256-o/4XqaRBKYcEPyhAvSRiWlL4kfav1nci5oUW4sncloI="
  [mod."github.com/cenkalti/backoff/v5"]
    version = "v5.0.2"
    hash = "sha256-AxtfsKIbXIx1eIOaA8GSMEoEvUJLBrWZSt7hSa2qhME="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.3.0"
    hash = "sha256-7hRlwSR+fos1kx4VZmJ/7snR7zHh8ZFKX+qqqqGcQpY="
  [mod."github.com/cubicdaiya/gonp"]
    version = "v1.0.4"
    hash = "sha256-EzI6qi2dYF/aCSNXe1zhoA24gaj6AFjHPwBbD2v7L64="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/denisbrodbeck/machineid"]
    version = "v1.0.1"
    hash = "sha256-K7ID9G3Caq31ahbe8b8ym/Wx5pRDIMO4TIrC5MTCuRw="
  [mod."github.com/dgraph-io/badger/v4"]
    version = "v4.7.0"
    hash = "sha256-er6vMBfBtX3FG7PbKcNU6e9OtrVKO1PfXySkea10AGM="
  [mod."github.com/dgraph-io/ristretto/v2"]
    version = "v2.2.0"
    hash = "sha256-FlyrD0i02l8Vh7DnS+R+t0En1IoMliEQIDvhGA+hXus="
  [mod."github.com/dgryski/go-rendezvous"]
    version = "v0.0.0-20200823014737-9f7001d12a5f"
    hash = "sha256-n/7xo5CQqo4yLaWMSzSN1Muk/oqK6O5dgDOFWapeDUI="
  [mod."github.com/dprotaso/go-yit"]
    version = "v0.0.0-20250513224043-18a80f8f6df4"
    hash = "sha256-gfGSv6gAAPys2V0vOuXa69QcMTecvuCNRM4DM8qrxDk="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fatih/structtag"]
    version = "v1.2.0"
    hash = "sha256-Y2pjiEmMsxfUH8LONU2/f8k1BibOHeLKJmi4uZm/SSU="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/getkin/kin-openapi"]
    version = "v0.132.0"
    hash = "sha256-UH6r1Pk0QQkO4rSPZIsuS+SdVAa7XBN+D67FokC4HwY="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.2.2"
    hash = "sha256-F+KxLJNRQxkjQCDlJ72MT/YS8cybKPsLeWOjo6HqJHU="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.3"
    hash = "sha256-Nnp/dEVNMxLp3RSPDHZzGbI8BkSNuZMX0I0cjWKXXLA="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.21.1"
    hash = "sha256-Ro8GxGOukP1vYzr8PT794ABdG/ssp4I3t+BrceUmQyY="
  [mod."github.com/go-openapi/swag"]
    version = "v0.23.1"
    hash = "sha256-M0aKOkI4YC8tOUT1SlpUylnjZoshhrDRy0hF4roqC1I="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.9.3"
    hash = "sha256-37CNj7G2S20w98rVAyFiScHQ5uXI/NSYY6Gsl41UwgY="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.5"
    hash = "sha256-/EtlGihP0/7oInzMC5E0InZ4b5Ad3s4xOpqotloi3xw="
  [mod."github.com/google/cel-go"]
    version = "v0.25.0"
    hash = "sha256-Ztdz/MKqt5SJzjXnJS/MeZ+ekEqENQtZDsZiufcUHL8="
  [mod."github.com/google/flatbuffers"]
    version = "v25.2.10+incompatible"
    hash = "sha256-qWFf58zxZzIdn+5dB9VRbhYPcZb39tCG/ePfC9dgn3M="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/grpc-ecosystem/grpc-gateway/v2"]
    version = "v2.26.3"
    hash = "sha256-j/nyE8OgiwZ1YP0h3gmmxY1Fx4GDMCohi9g9kgNz4U8="
  [mod."github.com/hashicorp/errwrap"]
    version = "v1.1.0"
    hash = "sha256-6lwuMQOfBq+McrViN3maJTIeh4f8jbEqvLy2c9FvvFw="
  [mod."github.com/hashicorp/go-multierror"]
    version = "v1.1.1"
    hash = "sha256-ANzPEUJIZIlToxR89Mn7Db73d9LGI51ssy7eNnUgmlA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.7.5"
    hash = "sha256-+bzuXlJnsvNEGjuhHIiZwmWepEmwj3Fl1ktLD50IKlU="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/klauspost/compress"]
    version = "v1.18.0"
    hash = "sha256-jc5pMU/HCBFOShMcngVwNMhz9wolxjOb579868LtOuk="
  [mod."github.com/mailru/easyjson"]
    version = "v0.9.0"
    hash = "sha256-CWeL+s/xX6LHum3GAtzH0/A//7EsZ24DpvTTXpi3dIE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mohae/deepcopy"]
    version = "v0.0.0-20170929034955-c48cc78d4826"
    hash = "sha256-TQMmKqIYwVhmMVh4RYQkAui97Eyj7poLmcAuDcHXsEk="
  [mod."github.com/ncruces/go-strftime"]
    version = "v0.1.9"
    hash = "sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY="
  [mod."github.com/oapi-codegen/oapi-codegen/v2"]
    version = "v2.4.1"
    hash = "sha256-brD8yF5MqJKWYtu9h2SEfax6NCmS2NnmA2yed/YeybA="
  [mod."github.com/oasdiff/yaml"]
    version = "v0.0.0-20250309154309-f31be36b4037"
    hash = "sha256-8K/OpDx7hwlloOaDkeOO6VmuoZs7MY7pYoJDWLNdvkw="
  [mod."github.com/oasdiff/yaml3"]
    version = "v0.0.0-20250309153720-d2182401db90"
    hash = "sha256-egJOh0zRxlaDhQNdDao0qV7Tpsqe1sU/868PRIrl2Ag="
  [mod."github.com/perimeterx/marshmallow"]
    version = "v1.1.5"
    hash = "sha256-fFWjg0FNohDSV0/wUjQ8fBq1g8h6yIqTrHkxqL2Tt0s="
  [mod."github.com/pganalyze/pg_query_go/v6"]
    version = "v6.1.0"
    hash = "sha256-oErZSMlN7WblwPNA48tYvcXgP9iCQP9KZHAYegkTHyg="
  [mod."github.com/pingcap/errors"]
    version = "v0.11.5-0.20240311024730-e056997136bb"
    hash = "sha256-ZjY2GTtFn8BPKDSIQ2RQoxgVXOXRb9KCh8aoruj/zFw="
  [mod."github.com/pingcap/failpoint"]
    version = "v0.0.0-20240528011301-b51a646c7c86"
    hash = "sha256-ivsfJW5MdgAjFqvd05Prjo78h5bh59ZzhPOjqXlpGkU="
  [mod."github.com/pingcap/log"]
    version = "v1.1.0"
    hash = "sha256-JT33CJMknTXha1ERt4s6vV9fyx99J+Ot8rFrNKXTsTc="
  [mod."github.com/pingcap/tidb/pkg/parser"]
    version = "v0.0.0-20250613120101-5b778e9129f0"
    hash = "sha256-8KD35PqpMmSbDRd7DiGutZSL22pJjTshWiSovy+GHfA="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/redis/go-redis/extra/rediscmd/v9"]
    version = "v9.10.0"
    hash = "sha256-DS7aSAs+iZCHaIQb24zJDnv2OC4iNCWG8NESSGYHxWs="
  [mod."github.com/redis/go-redis/extra/redisotel/v9"]
    version = "v9.10.0"
    hash = "sha256-mV87byzd5wSmOT+nmKx1rTHCXdgC7+Zwxa2lq+Azmng="
  [mod."github.com/redis/go-redis/v9"]
    version = "v9.10.0"
    hash = "sha256-fy6X1t23arortxe93bklp25LRLjO9VfYWyclEiZEue0="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/riza-io/grpc-go"]
    version = "v0.2.0"
    hash = "sha256-toqQdnwlcKbJHl1mv9cDBwRfyXAMBwbfun+yC9+Rwgw="
  [mod."github.com/speakeasy-api/jsonpath"]
    version = "v0.6.2"
    hash = "sha256-LbM9eYSwriiIJL7SZMT+3SPMVkMMNNpNIW6cWVKaYFk="
  [mod."github.com/speakeasy-api/openapi-overlay"]
    version = "v0.10.2"
    hash = "sha256-7EzV8q7kEM2uQQ2iLIaKXBG5GDNyT/mlgAMg+uDLi7I="
  [mod."github.com/spf13/cobra"]
    version = "v1.9.1"
    hash = "sha256-dzEqquABE3UqZmJuj99244QjvfojS8cFlsPr/MXQGj0="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.6"
    hash = "sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI="
  [mod."github.com/sqlc-dev/sqlc"]
    version = "v1.29.0"
    hash = "sha256-FtgueQtyQC0wizhrZXL4dFqrsFNHNK6WBNG+dF/vsow="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.3.0"
    hash = "sha256-X0ilcefeqVQ44B9WT6euCMcigs7oLFypOQaGI33kGr8="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/tetratelabs/wazero"]
    version = "v1.9.0"
    hash = "sha256-b8D0cDMuDgyjvJ6LFY8REdcL95BIjM27SeOEQWfB0+0="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.27"
    hash = "sha256-vq8NNTnoOHMkF56aEXKm6LMgY9FgagqCqPbi5NTtAoI="
  [mod."github.com/vmware-labs/yaml-jsonpath"]
    version = "v0.3.2"
    hash = "sha256-BZiEtlTVjwtLFaqYu1005t0yFc1/D1iNeabnsAtSXRY="
  [mod."github.com/wadey/gocovmerge"]
    version = "v0.0.0-20160331181800-b5bfa59ec0ad"
    hash = "sha256-YbA4t26v6frdkh0uiXtmi8hiDYjR/FPBTxTwWlmfpwI="
  [mod."github.com/wasilibs/go-pgquery"]
    version = "v0.0.0-20250409022910-10ac41983c07"
    hash = "sha256-627pU7bo9+lKbxQ6VqKFPK8wwQ/glvHCU2SRwzXIvog="
  [mod."github.com/wasilibs/wazero-helpers"]
    version = "v0.0.0-20250123031827-cd30c44769bb"
    hash = "sha256-SIpxqycUfIabJ0tsKmo0A4mDgUr35qNCenC+1Oy0GN0="
  [mod."github.com/wwmoraes/gotell"]
    version = "v0.5.0"
    hash = "sha256-aim9ybeFJ0cpi0D6qTLCDmmYeUMVjDOYatZUdtCdsSc="
  [mod."go.etcd.io/bbolt"]
    version = "v1.4.1"
    hash = "sha256-FqKrJJxOOfAnvziKKFzI6VUGDp+ga6IgZmuihHp2I2A="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"]
    version = "v0.61.0"
    hash = "sha256-o5w9k3VbqP3gaXI3Aelw93LLHH53U4PnkYVwc3MaY3Y="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.61.0"
    hash = "sha256-4pfXD7ErXhexSynXiEEQSAkWoPwHd7PEDE3M1Zi5gLM="
  [mod."go.opentelemetry.io/contrib/instrumentation/runtime"]
    version = "v0.61.0"
    hash = "sha256-q3sb66cqt1bd9/V6pVU3S6Yv0bBOXz0dBfjLBeqhGhY="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.37.0"
    hash = "sha256-zWpyp9K8/Te86uhNjamchZctTdAnmHhoVw9m4ACfSoo="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc"]
    version = "v0.12.2"
    hash = "sha256-ce2T/lfhvHp3lbq/VIcRUUfZn9yujcixHdIVcmTadrU="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"]
    version = "v1.36.0"
    hash = "sha256-YCfg3gvMP3i1OTER9v8m6Vm+hfMkJMOxfM/Lw3nmPqs="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.36.0"
    hash = "sha256-c1T2xgjMLra3GmJAQvN41zVt1k5V2+jBe2s0QaRw7C4="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.36.0"
    hash = "sha256-HW8IMrV9YoYHIvMB+/nL6GAaDwnnZpWPb4WE1eNT8OQ="
  [mod."go.opentelemetry.io/otel/log"]
    version = "v0.12.2"
    hash = "sha256-rok+1fNRKTvZ7eOPFDL1PW6uXd9i7O8CeNlwxzKdSAY="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.37.0"
    hash = "sha256-BWnkdldA3xzGhnaConzMAuQzOnugytIvrP6GjkZVAYg="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.37.0"
    hash = "sha256-uNFhKuSRhf+SXwVu8mg/qqsVio7KstVN/WyCTxgWHT0="
  [mod."go.opentelemetry.io/otel/sdk/log"]
    version = "v0.12.2"
    hash = "sha256-PCSL1opOUTfB77OUtrqjlaA8qM7wVSIomvrvwZnhees="
  [mod."go.opentelemetry.io/otel/sdk/metric"]
    version = "v1.36.0"
    hash = "sha256-kCJXX26+jXz/bFBpnNmFi6r+EusDXsy24tk7FgQbVgA="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.37.0"
    hash = "sha256-FBeLOb5qmIiE9VmbgCf1l/xpndBqHkRiaPt1PvoKrVY="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v1.7.0"
    hash = "sha256-wqmUA6XGjODfuTCRQs32tYFkvO717ZGyZYZFcbNHvLw="
  [mod."go.uber.org/atomic"]
    version = "v1.11.0"
    hash = "sha256-TyYws/cSPVqYNffFX0gbDml1bD4bBGcysrUWU7mHPIY="
  [mod."go.uber.org/automaxprocs"]
    version = "v1.6.0"
    hash = "sha256-a/Agm+kM9x+VRo0CYyTL3ipUYv9Glrc4NeGSZJdpobA="
  [mod."go.uber.org/multierr"]
    version = "v1.11.0"
    hash = "sha256-Lb6rHHfR62Ozg2j2JZy3MKOMKdsfzd1IYTR57r3Mhp0="
  [mod."go.uber.org/zap"]
    version = "v1.27.0"
    hash = "sha256-8655KDrulc4Das3VRduO9MjCn8ZYD5WkULjCvruaYsU="
  [mod."golang.org/x/crypto"]
    version = "v0.40.0"
    hash = "sha256-I6p2fqvz63P9MwAuoQrljI7IUbfZQvCem0ii4Q2zZng="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250606033433-dcc06ee1d476"
    hash = "sha256-6l2SmFtORAIXmsWGWrseCCR0HCoMd3Tpxdus00mJh3Q="
  [mod."golang.org/x/mod"]
    version = "v0.26.0"
    hash = "sha256-Ky2Z24x89S71fuuIKY1zwG3JttPmOfk+Mv/6YVT+CmM="
  [mod."golang.org/x/net"]
    version = "v0.42.0"
    hash = "sha256-YxileisIIez+kcAI+21kY5yk0iRuEqti2YdmS8jvP2s="
  [mod."golang.org/x/sync"]
    version = "v0.16.0"
    hash = "sha256-sqKDRESeMzLe0jWGWltLZL/JIgrn0XaIeBWCzVN3Bks="
  [mod."golang.org/x/sys"]
    version = "v0.34.0"
    hash = "sha256-5rZ7p8IaGli5X1sJbfIKOcOEwY4c0yQhinJPh2EtK50="
  [mod."golang.org/x/text"]
    version = "v0.27.0"
    hash = "sha256-VX0rOh6L3qIvquKSGjfZQFU8URNtGvkNvxE7OZtboW8="
  [mod."golang.org/x/time"]
    version = "v0.12.0"
    hash = "sha256-Cp3oxrCMH2wyxjzr5SHVmyhgaoUuSl56Uy00Q7DYEpw="
  [mod."golang.org/x/tools"]
    version = "v0.35.0"
    hash = "sha256-5aTV8oS9e0frUNUE2Pw+yTnPLghmZHryDa01COSyrCM="
  [mod."google.golang.org/genproto/googleapis/api"]
    version = "v0.0.0-20250603155806-513f23925822"
    hash = "sha256-0CS432v9zVhkVLqFpZtxBX8rvVqP67lb7qQ3es7RqIU="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20250603155806-513f23925822"
    hash = "sha256-WK7iDtAhH19NPe3TywTQlGjDawNaDKWnxhFL9PgVUwM="
  [mod."google.golang.org/grpc"]
    version = "v1.73.0"
    hash = "sha256-LfVlwip++q2DX70RU6CxoXglx1+r5l48DwlFD05G11c="
  [mod."google.golang.org/protobuf"]
    version = "v1.36.6"
    hash = "sha256-lT5qnefI5FDJnowz9PEkAGylH3+fE+A3DJDkAyy9RMc="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.2.1"
    hash = "sha256-GaXWRDxhGy4Z4mgE+bJ8OE9SVvYUa9TnNiydnp2s1Ms="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."modernc.org/libc"]
    version = "v1.65.10"
    hash = "sha256-3wAZuXQ5ClIlu+dkw5gDE6LXU1ZlVYZocPPQ/DmDbkQ="
  [mod."modernc.org/mathutil"]
    version = "v1.7.1"
    hash = "sha256-COZ5rF2GhQVR1r6a0DanJ8qwQ94JSKdQxTMWrDzE0Cc="
  [mod."modernc.org/memory"]
    version = "v1.11.0"
    hash = "sha256-MkybF8vvrxXS5j7O8w3skwTo0aMo1yjWS0K440rYcHM="
  [mod."modernc.org/sqlite"]
    version = "v1.38.0"
    hash = "sha256-EBhVvFid84h9MyEDk5MNc/SMjkI0llw8mCJsf5YoWoM="
