// Code generated by go generate. DO NOT EDIT.

package telemetry

const (
	ENVIRONMENT = "development"
	MODULE      = "github.com/wwmoraes/anilistarr"
	VERSION     = "0.1.0-rc.1"
	NAME        = "anilistarr"
	NAMESPACE   = "api"
)
