// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

type Cache struct {
	Key   string
	Value string
}

type Media struct {
	SourceID string
	TargetID string
}

type User struct {
	ID   string
	Name string
}
