// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"io/fs"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFS creates a new instance of MockFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFS {
	mock := &MockFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFS is an autogenerated mock type for the FS type
type MockFS struct {
	mock.Mock
}

type MockFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFS) EXPECT() *MockFS_Expecter {
	return &MockFS_Expecter{mock: &_m.Mock}
}

// Open provides a mock function for the type MockFS
func (_mock *MockFS) Open(name string) (fs.File, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 fs.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (fs.File, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) fs.File); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFS_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockFS_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - name string
func (_e *MockFS_Expecter) Open(name interface{}) *MockFS_Open_Call {
	return &MockFS_Open_Call{Call: _e.mock.On("Open", name)}
}

func (_c *MockFS_Open_Call) Run(run func(name string)) *MockFS_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFS_Open_Call) Return(file fs.File, err error) *MockFS_Open_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFS_Open_Call) RunAndReturn(run func(name string) (fs.File, error)) *MockFS_Open_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFile
func (_mock *MockFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(err error) *MockFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockFile
func (_mock *MockFile) Read(bytes []byte) (int, error) {
	ret := _mock.Called(bytes)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(bytes)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(bytes)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(bytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockFile_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - bytes []byte
func (_e *MockFile_Expecter) Read(bytes interface{}) *MockFile_Read_Call {
	return &MockFile_Read_Call{Call: _e.mock.On("Read", bytes)}
}

func (_c *MockFile_Read_Call) Run(run func(bytes []byte)) *MockFile_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFile_Read_Call) Return(n int, err error) *MockFile_Read_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFile_Read_Call) RunAndReturn(run func(bytes []byte) (int, error)) *MockFile_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockFile
func (_mock *MockFile) Stat() (fs.FileInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 fs.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (fs.FileInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() fs.FileInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fs.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockFile_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *MockFile_Expecter) Stat() *MockFile_Stat_Call {
	return &MockFile_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *MockFile_Stat_Call) Run(run func()) *MockFile_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Stat_Call) Return(fileInfo fs.FileInfo, err error) *MockFile_Stat_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *MockFile_Stat_Call) RunAndReturn(run func() (fs.FileInfo, error)) *MockFile_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileInfo creates a new instance of MockFileInfo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileInfo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileInfo {
	mock := &MockFileInfo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileInfo is an autogenerated mock type for the FileInfo type
type MockFileInfo struct {
	mock.Mock
}

type MockFileInfo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileInfo) EXPECT() *MockFileInfo_Expecter {
	return &MockFileInfo_Expecter{mock: &_m.Mock}
}

// IsDir provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) IsDir() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsDir")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockFileInfo_IsDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDir'
type MockFileInfo_IsDir_Call struct {
	*mock.Call
}

// IsDir is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) IsDir() *MockFileInfo_IsDir_Call {
	return &MockFileInfo_IsDir_Call{Call: _e.mock.On("IsDir")}
}

func (_c *MockFileInfo_IsDir_Call) Run(run func()) *MockFileInfo_IsDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_IsDir_Call) Return(b bool) *MockFileInfo_IsDir_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockFileInfo_IsDir_Call) RunAndReturn(run func() bool) *MockFileInfo_IsDir_Call {
	_c.Call.Return(run)
	return _c
}

// ModTime provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) ModTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ModTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockFileInfo_ModTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModTime'
type MockFileInfo_ModTime_Call struct {
	*mock.Call
}

// ModTime is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) ModTime() *MockFileInfo_ModTime_Call {
	return &MockFileInfo_ModTime_Call{Call: _e.mock.On("ModTime")}
}

func (_c *MockFileInfo_ModTime_Call) Run(run func()) *MockFileInfo_ModTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_ModTime_Call) Return(time1 time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockFileInfo_ModTime_Call) RunAndReturn(run func() time.Time) *MockFileInfo_ModTime_Call {
	_c.Call.Return(run)
	return _c
}

// Mode provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Mode() fs.FileMode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mode")
	}

	var r0 fs.FileMode
	if returnFunc, ok := ret.Get(0).(func() fs.FileMode); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(fs.FileMode)
	}
	return r0
}

// MockFileInfo_Mode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mode'
type MockFileInfo_Mode_Call struct {
	*mock.Call
}

// Mode is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Mode() *MockFileInfo_Mode_Call {
	return &MockFileInfo_Mode_Call{Call: _e.mock.On("Mode")}
}

func (_c *MockFileInfo_Mode_Call) Run(run func()) *MockFileInfo_Mode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Mode_Call) Return(fileMode fs.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(fileMode)
	return _c
}

func (_c *MockFileInfo_Mode_Call) RunAndReturn(run func() fs.FileMode) *MockFileInfo_Mode_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileInfo_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockFileInfo_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Name() *MockFileInfo_Name_Call {
	return &MockFileInfo_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockFileInfo_Name_Call) Run(run func()) *MockFileInfo_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Name_Call) Return(s string) *MockFileInfo_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileInfo_Name_Call) RunAndReturn(run func() string) *MockFileInfo_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockFileInfo_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockFileInfo_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Size() *MockFileInfo_Size_Call {
	return &MockFileInfo_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockFileInfo_Size_Call) Run(run func()) *MockFileInfo_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Size_Call) Return(n int64) *MockFileInfo_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockFileInfo_Size_Call) RunAndReturn(run func() int64) *MockFileInfo_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Sys provides a mock function for the type MockFileInfo
func (_mock *MockFileInfo) Sys() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sys")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockFileInfo_Sys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sys'
type MockFileInfo_Sys_Call struct {
	*mock.Call
}

// Sys is a helper method to define mock.On call
func (_e *MockFileInfo_Expecter) Sys() *MockFileInfo_Sys_Call {
	return &MockFileInfo_Sys_Call{Call: _e.mock.On("Sys")}
}

func (_c *MockFileInfo_Sys_Call) Run(run func()) *MockFileInfo_Sys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileInfo_Sys_Call) Return(v any) *MockFileInfo_Sys_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockFileInfo_Sys_Call) RunAndReturn(run func() any) *MockFileInfo_Sys_Call {
	_c.Call.Return(run)
	return _c
}
