// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"github.com/go-logr/logr"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogSink creates a new instance of MockLogSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogSink {
	mock := &MockLogSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogSink is an autogenerated mock type for the LogSink type
type MockLogSink struct {
	mock.Mock
}

type MockLogSink_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogSink) EXPECT() *MockLogSink_Expecter {
	return &MockLogSink_Expecter{mock: &_m.Mock}
}

// Enabled provides a mock function for the type MockLogSink
func (_mock *MockLogSink) Enabled(level int) bool {
	ret := _mock.Called(level)

	if len(ret) == 0 {
		panic("no return value specified for Enabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(level)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockLogSink_Enabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enabled'
type MockLogSink_Enabled_Call struct {
	*mock.Call
}

// Enabled is a helper method to define mock.On call
//   - level int
func (_e *MockLogSink_Expecter) Enabled(level interface{}) *MockLogSink_Enabled_Call {
	return &MockLogSink_Enabled_Call{Call: _e.mock.On("Enabled", level)}
}

func (_c *MockLogSink_Enabled_Call) Run(run func(level int)) *MockLogSink_Enabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogSink_Enabled_Call) Return(b bool) *MockLogSink_Enabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockLogSink_Enabled_Call) RunAndReturn(run func(level int) bool) *MockLogSink_Enabled_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockLogSink
func (_mock *MockLogSink) Error(err error, msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(err, msg, keysAndValues)
	} else {
		_mock.Called(err, msg)
	}

	return
}

// MockLogSink_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogSink_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogSink_Expecter) Error(err interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogSink_Error_Call {
	return &MockLogSink_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{err, msg}, keysAndValues...)...)}
}

func (_c *MockLogSink_Error_Call) Run(run func(err error, msg string, keysAndValues ...any)) *MockLogSink_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogSink_Error_Call) Return() *MockLogSink_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Error_Call) RunAndReturn(run func(err error, msg string, keysAndValues ...any)) *MockLogSink_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogSink
func (_mock *MockLogSink) Info(level int, msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(level, msg, keysAndValues)
	} else {
		_mock.Called(level, msg)
	}

	return
}

// MockLogSink_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogSink_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - level int
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogSink_Expecter) Info(level interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogSink_Info_Call {
	return &MockLogSink_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{level, msg}, keysAndValues...)...)}
}

func (_c *MockLogSink_Info_Call) Run(run func(level int, msg string, keysAndValues ...any)) *MockLogSink_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogSink_Info_Call) Return() *MockLogSink_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Info_Call) RunAndReturn(run func(level int, msg string, keysAndValues ...any)) *MockLogSink_Info_Call {
	_c.Run(run)
	return _c
}

// Init provides a mock function for the type MockLogSink
func (_mock *MockLogSink) Init(info logr.RuntimeInfo) {
	_mock.Called(info)
	return
}

// MockLogSink_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockLogSink_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - info logr.RuntimeInfo
func (_e *MockLogSink_Expecter) Init(info interface{}) *MockLogSink_Init_Call {
	return &MockLogSink_Init_Call{Call: _e.mock.On("Init", info)}
}

func (_c *MockLogSink_Init_Call) Run(run func(info logr.RuntimeInfo)) *MockLogSink_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 logr.RuntimeInfo
		if args[0] != nil {
			arg0 = args[0].(logr.RuntimeInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogSink_Init_Call) Return() *MockLogSink_Init_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogSink_Init_Call) RunAndReturn(run func(info logr.RuntimeInfo)) *MockLogSink_Init_Call {
	_c.Run(run)
	return _c
}

// WithName provides a mock function for the type MockLogSink
func (_mock *MockLogSink) WithName(name string) logr.LogSink {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for WithName")
	}

	var r0 logr.LogSink
	if returnFunc, ok := ret.Get(0).(func(string) logr.LogSink); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logr.LogSink)
		}
	}
	return r0
}

// MockLogSink_WithName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithName'
type MockLogSink_WithName_Call struct {
	*mock.Call
}

// WithName is a helper method to define mock.On call
//   - name string
func (_e *MockLogSink_Expecter) WithName(name interface{}) *MockLogSink_WithName_Call {
	return &MockLogSink_WithName_Call{Call: _e.mock.On("WithName", name)}
}

func (_c *MockLogSink_WithName_Call) Run(run func(name string)) *MockLogSink_WithName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLogSink_WithName_Call) Return(logSink logr.LogSink) *MockLogSink_WithName_Call {
	_c.Call.Return(logSink)
	return _c
}

func (_c *MockLogSink_WithName_Call) RunAndReturn(run func(name string) logr.LogSink) *MockLogSink_WithName_Call {
	_c.Call.Return(run)
	return _c
}

// WithValues provides a mock function for the type MockLogSink
func (_mock *MockLogSink) WithValues(keysAndValues ...any) logr.LogSink {
	var tmpRet mock.Arguments
	if len(keysAndValues) > 0 {
		tmpRet = _mock.Called(keysAndValues)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WithValues")
	}

	var r0 logr.LogSink
	if returnFunc, ok := ret.Get(0).(func(...any) logr.LogSink); ok {
		r0 = returnFunc(keysAndValues...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logr.LogSink)
		}
	}
	return r0
}

// MockLogSink_WithValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithValues'
type MockLogSink_WithValues_Call struct {
	*mock.Call
}

// WithValues is a helper method to define mock.On call
//   - keysAndValues ...any
func (_e *MockLogSink_Expecter) WithValues(keysAndValues ...interface{}) *MockLogSink_WithValues_Call {
	return &MockLogSink_WithValues_Call{Call: _e.mock.On("WithValues",
		append([]interface{}{}, keysAndValues...)...)}
}

func (_c *MockLogSink_WithValues_Call) Run(run func(keysAndValues ...any)) *MockLogSink_WithValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogSink_WithValues_Call) Return(logSink logr.LogSink) *MockLogSink_WithValues_Call {
	_c.Call.Return(logSink)
	return _c
}

func (_c *MockLogSink_WithValues_Call) RunAndReturn(run func(keysAndValues ...any) logr.LogSink) *MockLogSink_WithValues_Call {
	_c.Call.Return(run)
	return _c
}
