// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package test

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
	"github.com/wwmoraes/anilistarr/internal/entities"
	"github.com/wwmoraes/anilistarr/internal/usecases"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockCache
func (_mock *MockCache) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockCache_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockCache_Expecter) Close() *MockCache_Close_Call {
	return &MockCache_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockCache_Close_Call) Run(run func()) *MockCache_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCache_Close_Call) Return(err error) *MockCache_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_Close_Call) RunAndReturn(run func() error) *MockCache_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetString provides a mock function for the type MockCache
func (_mock *MockCache) GetString(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetString")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetString'
type MockCache_GetString_Call struct {
	*mock.Call
}

// GetString is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) GetString(ctx interface{}, key interface{}) *MockCache_GetString_Call {
	return &MockCache_GetString_Call{Call: _e.mock.On("GetString", ctx, key)}
}

func (_c *MockCache_GetString_Call) Run(run func(ctx context.Context, key string)) *MockCache_GetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetString_Call) Return(s string, err error) *MockCache_GetString_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCache_GetString_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *MockCache_GetString_Call {
	_c.Call.Return(run)
	return _c
}

// SetString provides a mock function for the type MockCache
func (_mock *MockCache) SetString(ctx context.Context, key string, value string, options ...usecases.CacheOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, key, value, options)
	} else {
		tmpRet = _mock.Called(ctx, key, value)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetString")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...usecases.CacheOption) error); ok {
		r0 = returnFunc(ctx, key, value, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SetString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetString'
type MockCache_SetString_Call struct {
	*mock.Call
}

// SetString is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - options ...usecases.CacheOption
func (_e *MockCache_Expecter) SetString(ctx interface{}, key interface{}, value interface{}, options ...interface{}) *MockCache_SetString_Call {
	return &MockCache_SetString_Call{Call: _e.mock.On("SetString",
		append([]interface{}{ctx, key, value}, options...)...)}
}

func (_c *MockCache_SetString_Call) Run(run func(ctx context.Context, key string, value string, options ...usecases.CacheOption)) *MockCache_SetString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []usecases.CacheOption
		var variadicArgs []usecases.CacheOption
		if len(args) > 3 {
			variadicArgs = args[3].([]usecases.CacheOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockCache_SetString_Call) Return(err error) *MockCache_SetString_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SetString_Call) RunAndReturn(run func(ctx context.Context, key string, value string, options ...usecases.CacheOption) error) *MockCache_SetString_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockDoer
func (_mock *MockDoer) Do(req *http.Request) (*http.Response, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req *http.Request
func (_e *MockDoer_Expecter) Do(req interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockDoer_Do_Call) Run(run func(req *http.Request)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.Request
		if args[0] != nil {
			arg0 = args[0].(*http.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(response *http.Response, err error) *MockDoer_Do_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(req *http.Request) (*http.Response, error)) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetter creates a new instance of MockGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetter {
	mock := &MockGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGetter is an autogenerated mock type for the Getter type
type MockGetter struct {
	mock.Mock
}

type MockGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetter) EXPECT() *MockGetter_Expecter {
	return &MockGetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockGetter
func (_mock *MockGetter) Get(ctx context.Context, uri string) ([]byte, error) {
	ret := _mock.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return returnFunc(ctx, uri)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = returnFunc(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uri string
func (_e *MockGetter_Expecter) Get(ctx interface{}, uri interface{}) *MockGetter_Get_Call {
	return &MockGetter_Get_Call{Call: _e.mock.On("Get", ctx, uri)}
}

func (_c *MockGetter_Get_Call) Run(run func(ctx context.Context, uri string)) *MockGetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGetter_Get_Call) Return(bytes []byte, err error) *MockGetter_Get_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockGetter_Get_Call) RunAndReturn(run func(ctx context.Context, uri string) ([]byte, error)) *MockGetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaLister creates a new instance of MockMediaLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaLister {
	mock := &MockMediaLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMediaLister is an autogenerated mock type for the MediaLister type
type MockMediaLister struct {
	mock.Mock
}

type MockMediaLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaLister) EXPECT() *MockMediaLister_Expecter {
	return &MockMediaLister_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaLister_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMediaLister_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMediaLister_Expecter) Close() *MockMediaLister_Close_Call {
	return &MockMediaLister_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMediaLister_Close_Call) Run(run func()) *MockMediaLister_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMediaLister_Close_Call) Return(err error) *MockMediaLister_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaLister_Close_Call) RunAndReturn(run func() error) *MockMediaLister_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Generate provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) Generate(ctx context.Context, name string) (entities.CustomList, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 entities.CustomList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (entities.CustomList, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) entities.CustomList); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entities.CustomList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaLister_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockMediaLister_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMediaLister_Expecter) Generate(ctx interface{}, name interface{}) *MockMediaLister_Generate_Call {
	return &MockMediaLister_Generate_Call{Call: _e.mock.On("Generate", ctx, name)}
}

func (_c *MockMediaLister_Generate_Call) Run(run func(ctx context.Context, name string)) *MockMediaLister_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaLister_Generate_Call) Return(customList entities.CustomList, err error) *MockMediaLister_Generate_Call {
	_c.Call.Return(customList, err)
	return _c
}

func (_c *MockMediaLister_Generate_Call) RunAndReturn(run func(ctx context.Context, name string) (entities.CustomList, error)) *MockMediaLister_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) GetUserID(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaLister_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockMediaLister_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMediaLister_Expecter) GetUserID(ctx interface{}, name interface{}) *MockMediaLister_GetUserID_Call {
	return &MockMediaLister_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx, name)}
}

func (_c *MockMediaLister_GetUserID_Call) Run(run func(ctx context.Context, name string)) *MockMediaLister_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaLister_GetUserID_Call) Return(s string, err error) *MockMediaLister_GetUserID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockMediaLister_GetUserID_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockMediaLister_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}

// MapIDs provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) MapIDs(ctx context.Context, ids []entities.SourceID) ([]entities.TargetID, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for MapIDs")
	}

	var r0 []entities.TargetID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.SourceID) ([]entities.TargetID, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entities.SourceID) []entities.TargetID); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.TargetID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []entities.SourceID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMediaLister_MapIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MapIDs'
type MockMediaLister_MapIDs_Call struct {
	*mock.Call
}

// MapIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []entities.SourceID
func (_e *MockMediaLister_Expecter) MapIDs(ctx interface{}, ids interface{}) *MockMediaLister_MapIDs_Call {
	return &MockMediaLister_MapIDs_Call{Call: _e.mock.On("MapIDs", ctx, ids)}
}

func (_c *MockMediaLister_MapIDs_Call) Run(run func(ctx context.Context, ids []entities.SourceID)) *MockMediaLister_MapIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []entities.SourceID
		if args[1] != nil {
			arg1 = args[1].([]entities.SourceID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaLister_MapIDs_Call) Return(vs []entities.TargetID, err error) *MockMediaLister_MapIDs_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockMediaLister_MapIDs_Call) RunAndReturn(run func(ctx context.Context, ids []entities.SourceID) ([]entities.TargetID, error)) *MockMediaLister_MapIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockMediaLister
func (_mock *MockMediaLister) Refresh(ctx context.Context, client usecases.Getter) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecases.Getter) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMediaLister_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockMediaLister_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - client usecases.Getter
func (_e *MockMediaLister_Expecter) Refresh(ctx interface{}, client interface{}) *MockMediaLister_Refresh_Call {
	return &MockMediaLister_Refresh_Call{Call: _e.mock.On("Refresh", ctx, client)}
}

func (_c *MockMediaLister_Refresh_Call) Run(run func(ctx context.Context, client usecases.Getter)) *MockMediaLister_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecases.Getter
		if args[1] != nil {
			arg1 = args[1].(usecases.Getter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMediaLister_Refresh_Call) Return(err error) *MockMediaLister_Refresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMediaLister_Refresh_Call) RunAndReturn(run func(ctx context.Context, client usecases.Getter) error) *MockMediaLister_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetadata creates a new instance of MockMetadata. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadata(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadata {
	mock := &MockMetadata{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadata is an autogenerated mock type for the Metadata type
type MockMetadata struct {
	mock.Mock
}

type MockMetadata_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadata) EXPECT() *MockMetadata_Expecter {
	return &MockMetadata_Expecter{mock: &_m.Mock}
}

// GetSourceID provides a mock function for the type MockMetadata
func (_mock *MockMetadata) GetSourceID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSourceID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMetadata_GetSourceID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSourceID'
type MockMetadata_GetSourceID_Call struct {
	*mock.Call
}

// GetSourceID is a helper method to define mock.On call
func (_e *MockMetadata_Expecter) GetSourceID() *MockMetadata_GetSourceID_Call {
	return &MockMetadata_GetSourceID_Call{Call: _e.mock.On("GetSourceID")}
}

func (_c *MockMetadata_GetSourceID_Call) Run(run func()) *MockMetadata_GetSourceID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadata_GetSourceID_Call) Return(s string) *MockMetadata_GetSourceID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMetadata_GetSourceID_Call) RunAndReturn(run func() string) *MockMetadata_GetSourceID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTargetID provides a mock function for the type MockMetadata
func (_mock *MockMetadata) GetTargetID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTargetID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMetadata_GetTargetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTargetID'
type MockMetadata_GetTargetID_Call struct {
	*mock.Call
}

// GetTargetID is a helper method to define mock.On call
func (_e *MockMetadata_Expecter) GetTargetID() *MockMetadata_GetTargetID_Call {
	return &MockMetadata_GetTargetID_Call{Call: _e.mock.On("GetTargetID")}
}

func (_c *MockMetadata_GetTargetID_Call) Run(run func()) *MockMetadata_GetTargetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadata_GetTargetID_Call) Return(s string) *MockMetadata_GetTargetID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMetadata_GetTargetID_Call) RunAndReturn(run func() string) *MockMetadata_GetTargetID_Call {
	_c.Call.Return(run)
	return _c
}

// Valid provides a mock function for the type MockMetadata
func (_mock *MockMetadata) Valid() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Valid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMetadata_Valid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Valid'
type MockMetadata_Valid_Call struct {
	*mock.Call
}

// Valid is a helper method to define mock.On call
func (_e *MockMetadata_Expecter) Valid() *MockMetadata_Valid_Call {
	return &MockMetadata_Valid_Call{Call: _e.mock.On("Valid")}
}

func (_c *MockMetadata_Valid_Call) Run(run func()) *MockMetadata_Valid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadata_Valid_Call) Return(b bool) *MockMetadata_Valid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMetadata_Valid_Call) RunAndReturn(run func() bool) *MockMetadata_Valid_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSource creates a new instance of MockSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSource {
	mock := &MockSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSource is an autogenerated mock type for the Source type
type MockSource struct {
	mock.Mock
}

type MockSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSource) EXPECT() *MockSource_Expecter {
	return &MockSource_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockSource
func (_mock *MockSource) Fetch(ctx context.Context, client usecases.Getter) ([]usecases.Metadata, error) {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []usecases.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecases.Getter) ([]usecases.Metadata, error)); ok {
		return returnFunc(ctx, client)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecases.Getter) []usecases.Metadata); ok {
		r0 = returnFunc(ctx, client)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]usecases.Metadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, usecases.Getter) error); ok {
		r1 = returnFunc(ctx, client)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSource_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockSource_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
//   - ctx context.Context
//   - client usecases.Getter
func (_e *MockSource_Expecter) Fetch(ctx interface{}, client interface{}) *MockSource_Fetch_Call {
	return &MockSource_Fetch_Call{Call: _e.mock.On("Fetch", ctx, client)}
}

func (_c *MockSource_Fetch_Call) Run(run func(ctx context.Context, client usecases.Getter)) *MockSource_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecases.Getter
		if args[1] != nil {
			arg1 = args[1].(usecases.Getter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSource_Fetch_Call) Return(metadatas []usecases.Metadata, err error) *MockSource_Fetch_Call {
	_c.Call.Return(metadatas, err)
	return _c
}

func (_c *MockSource_Fetch_Call) RunAndReturn(run func(ctx context.Context, client usecases.Getter) ([]usecases.Metadata, error)) *MockSource_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockSource
func (_mock *MockSource) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSource_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockSource_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockSource_Expecter) String() *MockSource_String_Call {
	return &MockSource_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockSource_String_Call) Run(run func()) *MockSource_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSource_String_Call) Return(s string) *MockSource_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSource_String_Call) RunAndReturn(run func() string) *MockSource_String_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStore
func (_mock *MockStore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(err error) *MockStore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetMedia provides a mock function for the type MockStore
func (_mock *MockStore) GetMedia(ctx context.Context, id string) (*entities.Media, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMedia")
	}

	var r0 *entities.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*entities.Media, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *entities.Media); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMedia'
type MockStore_GetMedia_Call struct {
	*mock.Call
}

// GetMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockStore_Expecter) GetMedia(ctx interface{}, id interface{}) *MockStore_GetMedia_Call {
	return &MockStore_GetMedia_Call{Call: _e.mock.On("GetMedia", ctx, id)}
}

func (_c *MockStore_GetMedia_Call) Run(run func(ctx context.Context, id string)) *MockStore_GetMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetMedia_Call) Return(media *entities.Media, err error) *MockStore_GetMedia_Call {
	_c.Call.Return(media, err)
	return _c
}

func (_c *MockStore_GetMedia_Call) RunAndReturn(run func(ctx context.Context, id string) (*entities.Media, error)) *MockStore_GetMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaBulk provides a mock function for the type MockStore
func (_mock *MockStore) GetMediaBulk(ctx context.Context, ids []string) ([]*entities.Media, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaBulk")
	}

	var r0 []*entities.Media
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*entities.Media, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*entities.Media); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Media)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_GetMediaBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaBulk'
type MockStore_GetMediaBulk_Call struct {
	*mock.Call
}

// GetMediaBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockStore_Expecter) GetMediaBulk(ctx interface{}, ids interface{}) *MockStore_GetMediaBulk_Call {
	return &MockStore_GetMediaBulk_Call{Call: _e.mock.On("GetMediaBulk", ctx, ids)}
}

func (_c *MockStore_GetMediaBulk_Call) Run(run func(ctx context.Context, ids []string)) *MockStore_GetMediaBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_GetMediaBulk_Call) Return(medias []*entities.Media, err error) *MockStore_GetMediaBulk_Call {
	_c.Call.Return(medias, err)
	return _c
}

func (_c *MockStore_GetMediaBulk_Call) RunAndReturn(run func(ctx context.Context, ids []string) ([]*entities.Media, error)) *MockStore_GetMediaBulk_Call {
	_c.Call.Return(run)
	return _c
}

// PutMedia provides a mock function for the type MockStore
func (_mock *MockStore) PutMedia(ctx context.Context, media *entities.Media) error {
	ret := _mock.Called(ctx, media)

	if len(ret) == 0 {
		panic("no return value specified for PutMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Media) error); ok {
		r0 = returnFunc(ctx, media)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PutMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMedia'
type MockStore_PutMedia_Call struct {
	*mock.Call
}

// PutMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - media *entities.Media
func (_e *MockStore_Expecter) PutMedia(ctx interface{}, media interface{}) *MockStore_PutMedia_Call {
	return &MockStore_PutMedia_Call{Call: _e.mock.On("PutMedia", ctx, media)}
}

func (_c *MockStore_PutMedia_Call) Run(run func(ctx context.Context, media *entities.Media)) *MockStore_PutMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Media
		if args[1] != nil {
			arg1 = args[1].(*entities.Media)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutMedia_Call) Return(err error) *MockStore_PutMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PutMedia_Call) RunAndReturn(run func(ctx context.Context, media *entities.Media) error) *MockStore_PutMedia_Call {
	_c.Call.Return(run)
	return _c
}

// PutMediaBulk provides a mock function for the type MockStore
func (_mock *MockStore) PutMediaBulk(ctx context.Context, medias []*entities.Media) error {
	ret := _mock.Called(ctx, medias)

	if len(ret) == 0 {
		panic("no return value specified for PutMediaBulk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []*entities.Media) error); ok {
		r0 = returnFunc(ctx, medias)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStore_PutMediaBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMediaBulk'
type MockStore_PutMediaBulk_Call struct {
	*mock.Call
}

// PutMediaBulk is a helper method to define mock.On call
//   - ctx context.Context
//   - medias []*entities.Media
func (_e *MockStore_Expecter) PutMediaBulk(ctx interface{}, medias interface{}) *MockStore_PutMediaBulk_Call {
	return &MockStore_PutMediaBulk_Call{Call: _e.mock.On("PutMediaBulk", ctx, medias)}
}

func (_c *MockStore_PutMediaBulk_Call) Run(run func(ctx context.Context, medias []*entities.Media)) *MockStore_PutMediaBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*entities.Media
		if args[1] != nil {
			arg1 = args[1].([]*entities.Media)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_PutMediaBulk_Call) Return(err error) *MockStore_PutMediaBulk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStore_PutMediaBulk_Call) RunAndReturn(run func(ctx context.Context, medias []*entities.Media) error) *MockStore_PutMediaBulk_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTracker creates a new instance of MockTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTracker {
	mock := &MockTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTracker is an autogenerated mock type for the Tracker type
type MockTracker struct {
	mock.Mock
}

type MockTracker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTracker) EXPECT() *MockTracker_Expecter {
	return &MockTracker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTracker
func (_mock *MockTracker) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTracker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTracker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTracker_Expecter) Close() *MockTracker_Close_Call {
	return &MockTracker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTracker_Close_Call) Run(run func()) *MockTracker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTracker_Close_Call) Return(err error) *MockTracker_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTracker_Close_Call) RunAndReturn(run func() error) *MockTracker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaListIDs provides a mock function for the type MockTracker
func (_mock *MockTracker) GetMediaListIDs(ctx context.Context, userID string) ([]entities.SourceID, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaListIDs")
	}

	var r0 []entities.SourceID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]entities.SourceID, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []entities.SourceID); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.SourceID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTracker_GetMediaListIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaListIDs'
type MockTracker_GetMediaListIDs_Call struct {
	*mock.Call
}

// GetMediaListIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTracker_Expecter) GetMediaListIDs(ctx interface{}, userID interface{}) *MockTracker_GetMediaListIDs_Call {
	return &MockTracker_GetMediaListIDs_Call{Call: _e.mock.On("GetMediaListIDs", ctx, userID)}
}

func (_c *MockTracker_GetMediaListIDs_Call) Run(run func(ctx context.Context, userID string)) *MockTracker_GetMediaListIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTracker_GetMediaListIDs_Call) Return(vs []entities.SourceID, err error) *MockTracker_GetMediaListIDs_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockTracker_GetMediaListIDs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]entities.SourceID, error)) *MockTracker_GetMediaListIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserID provides a mock function for the type MockTracker
func (_mock *MockTracker) GetUserID(ctx context.Context, name string) (string, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetUserID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTracker_GetUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserID'
type MockTracker_GetUserID_Call struct {
	*mock.Call
}

// GetUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockTracker_Expecter) GetUserID(ctx interface{}, name interface{}) *MockTracker_GetUserID_Call {
	return &MockTracker_GetUserID_Call{Call: _e.mock.On("GetUserID", ctx, name)}
}

func (_c *MockTracker_GetUserID_Call) Run(run func(ctx context.Context, name string)) *MockTracker_GetUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTracker_GetUserID_Call) Return(s string, err error) *MockTracker_GetUserID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTracker_GetUserID_Call) RunAndReturn(run func(ctx context.Context, name string) (string, error)) *MockTracker_GetUserID_Call {
	_c.Call.Return(run)
	return _c
}
