@startuml
set separator none
title GitHub - Containers

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>

System(Anilistarr, "Anilistarr", $descr="converts anime sources for *arr services", $tags="", $link="")

System_Boundary("GitHub_boundary", "GitHub", $tags="") {
  Container(GitHub.API, "API", $techn="REST", $descr="", $tags="", $link="")
}

Rel(Anilistarr, GitHub.API, "Uses", $techn="HTTP/REST", $tags="", $link="")

SHOW_LEGEND(true)
@enduml