@startuml
set separator none
title Github - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

System(Github, "Github", $descr="", $tags="", $link="")
System(Anilistarr, "Anilistarr", $descr="converts anime sources for *arr services", $tags="", $link="")

Rel(Anilistarr, Github, "Uses", $techn="HTTP", $tags="", $link="")

SHOW_LEGEND(true)
@enduml