@startuml
set separator none
title Radarr - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

System(Anilistarr, "Anilistarr", $descr="converts anime sources for *arr services", $tags="", $link="")
System(Radarr, "Radarr", $descr="", $tags="", $link="")

Rel(Radarr, Anilistarr, "Uses", $techn="HTTP/REST", $tags="", $link="")

SHOW_LEGEND(true)
@enduml