@startuml
set separator none
title Anilistarr - anilistarr - Components

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Container>
!include <C4/C4_Component>

System(Anilist, "Anilist", $descr="", $tags="", $link="")
System(GitHub, "GitHub", $descr="", $tags="", $link="")
ContainerDb(Anilistarr.Redis, "Redis", $techn="", $descr="", $tags="", $link="")
ContainerDb(Anilistarr.BoltDB, "BoltDB", $techn="", $descr="", $tags="", $link="")
ContainerDb(Anilistarr.BadgerDB, "BadgerDB", $techn="", $descr="", $tags="", $link="")
ContainerDb(Anilistarr.SQLite, "SQLite", $techn="", $descr="", $tags="", $link="")
System(Sonarr, "Sonarr", $descr="", $tags="", $link="")
System(Radarr, "Radarr", $descr="", $tags="", $link="")

Container_Boundary("Anilistarr.anilistarr_boundary", "anilistarr", $tags="") {
  AddBoundaryTag("drivers", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_1, "drivers", $tags="drivers") {
      AddBoundaryTag("drivers/caches | stores", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_2, "caches | stores", $tags="drivers/caches | stores") {
        Component(Anilistarr.anilistarr.BadgerDBDriver, "BadgerDB Driver", $techn="", $descr="", $tags="", $link="")
        Component(Anilistarr.anilistarr.BoltDBDriver, "BoltDB Driver", $techn="", $descr="", $tags="", $link="")
        Component(Anilistarr.anilistarr.RedisDriver, "Redis Driver", $techn="", $descr="", $tags="", $link="")
        Component(Anilistarr.anilistarr.SQLiteDriver, "SQLite Driver", $techn="", $descr="", $tags="", $link="")
      }

      AddBoundaryTag("drivers/providers", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_3, "providers", $tags="drivers/providers") {
        Component(Anilistarr.anilistarr.AnilistFribbsProvider, "Anilist Fribbs Provider", $techn="", $descr="", $tags="", $link="")
      }

      AddBoundaryTag("drivers/trackers", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
      Boundary(group_4, "trackers", $tags="drivers/trackers") {
        Component(Anilistarr.anilistarr.AnilistDriver, "Anilist Driver", $techn="struct", $descr="", $tags="", $link="")
      }

  }

  AddBoundaryTag("usecases", $borderColor="#cccccc", $fontColor="#cccccc", $borderStyle="dashed")
  Boundary(group_5, "usecases", $tags="usecases") {
    Component(Anilistarr.anilistarr.CachedTracker, "CachedTracker", $techn="", $descr="", $tags="", $link="")
    Component(Anilistarr.anilistarr.MediaList, "MediaList", $techn="", $descr="", $tags="", $link="")
  }

  Component(Anilistarr.anilistarr.API, "API", $techn="REST", $descr="", $tags="", $link="")
}

Rel(Anilistarr.anilistarr.AnilistDriver, Anilist, "Uses", $techn="HTTP/GraphQL", $tags="", $link="")
Rel(Anilistarr.anilistarr.BadgerDBDriver, Anilistarr.BadgerDB, "Uses", $techn="IPC", $tags="", $link="")
Rel(Anilistarr.anilistarr.BoltDBDriver, Anilistarr.BoltDB, "uses", $techn="IPC", $tags="", $link="")
Rel(Anilistarr.anilistarr.RedisDriver, Anilistarr.Redis, "uses", $techn="HTTP", $tags="", $link="")
Rel(Anilistarr.anilistarr.SQLiteDriver, Anilistarr.SQLite, "Uses", $techn="IPC", $tags="", $link="")
Rel(Anilistarr.anilistarr.AnilistFribbsProvider, GitHub, "Uses", $techn="HTTP/REST", $tags="", $link="")
Rel(Anilistarr.anilistarr.CachedTracker, Anilistarr.anilistarr.AnilistDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.CachedTracker, Anilistarr.anilistarr.BoltDBDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.CachedTracker, Anilistarr.anilistarr.RedisDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.CachedTracker, Anilistarr.anilistarr.BadgerDBDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.CachedTracker, Anilistarr.anilistarr.SQLiteDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.MediaList, Anilistarr.anilistarr.CachedTracker, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.MediaList, Anilistarr.anilistarr.AnilistFribbsProvider, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.MediaList, Anilistarr.anilistarr.BadgerDBDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.MediaList, Anilistarr.anilistarr.SQLiteDriver, "Uses", $techn="", $tags="", $link="")
Rel(Anilistarr.anilistarr.API, Anilistarr.anilistarr.MediaList, "Uses", $techn="", $tags="", $link="")
Rel(Sonarr, Anilistarr.anilistarr.API, "Uses", $techn="HTTP/REST", $tags="", $link="")
Rel(Radarr, Anilistarr.anilistarr.API, "Uses", $techn="HTTP/REST", $tags="", $link="")

SHOW_LEGEND(true)
@enduml