@startuml
set separator none
title Anilist - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

System(Anilist, "Anilist", $descr="", $tags="", $link="")
System(Anilistarr, "Anilistarr", $descr="converts anime sources for *arr services", $tags="", $link="")

Rel(Anilistarr, Anilist, "Uses", $techn="HTTP/GraphQL", $tags="", $link="")

SHOW_LEGEND(true)
@enduml