@startuml
set separator none
title Sonarr - System Context

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>

System(Anilistarr, "Anilistarr", $descr="converts anime sources for *arr services", $tags="", $link="")
System(Sonarr, "Sonarr", $descr="", $tags="", $link="")

Rel(Sonarr, Anilistarr, "Uses", $techn="HTTP/REST", $tags="", $link="")

SHOW_LEGEND(true)
@enduml