name: Integration
# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master
    - user/*/trunk
    tags-ignore:
    - "*"
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
  pull_request:
    branches:
    - master
    - user/*/trunk
    tags-ignore:
    - "*"
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
permissions:
  contents: read
  security-events: write
defaults:
  run:
    shell: bash
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v5
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
    - name: lint
      run: make sast check
      if: always()
    - name: build
      run: make all
    - name: test
      run: make test
    - name: report test
      run: make coverage-upload
      if: always()
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: report lint
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: sast.sarif
