name: Integration
on:
  push:
    branches:
    - master
    - user/*/trunk
    tags-ignore:
    - "*"
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
  pull_request:
    branches:
    - master
    - user/*/trunk
    tags-ignore:
    - "*"
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
permissions:
  contents: read
  security-events: write
defaults:
  run:
    shell: bash
env:
  DEVSHELL: ci
jobs:
  warmup:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 0
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@fc1182ab8fc636cdcef08176ad91e5c1087658d9 # v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: cache devshell
      run: nix develop --command true
  integrate:
    runs-on: ubuntu-latest
    needs: [warmup]
    steps:
    - name: checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@fc1182ab8fc636cdcef08176ad91e5c1087658d9 # v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: set up QEMU
      uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4.1.0
    - name: set up docker buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
    - name: build
      run: make all
    - name: lint
      run: make sast check
    - name: test
      run: make test
    - name: report test
      run: make coverage-upload
      continue-on-error: true
      if: always()
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: report lint
      uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4
      continue-on-error: true
      if: always()
      with:
        sarif_file: sast.sarif
