name: Release
on:
  push:
    tags:
    - '*'
permissions:
  contents: read
env:
  DEVSHELL: ci
jobs:
  release:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master'
      && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        fetch-depth: 0
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@fc1182ab8fc636cdcef08176ad91e5c1087658d9 # v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: binaries
      run: make dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: set up QEMU
      uses: docker/setup-qemu-action@4.1.0
    - name: set up docker buildx
      uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
    - name: login to DockerHub
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: container
      run: make image-push
    - name: update DockerHub description
      uses: meeDamian/sync-readme@82715041300710d9be7c726c9d6c683b70451087 # v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASSWORD }}
        description: true
