name: Release

# yamllint disable-line rule:truthy
on:
  push:
    tags:
    - '*'

permissions:
  contents: read

jobs:
  binaries:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master'
      && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: pre-fetch taskfile
      run: task --download --yes
    - name: cache modules
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${GOMODCACHE}
        key: ${{ runner.os }}-modules-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-modules-${{ hashFiles('go.sum') }}
          ${{ runner.os }}-modules-
    - name: cache build
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${GOCACHE}
        key: ${{ runner.os }}-build-${{ hashFiles('**/*.go') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ hashFiles('**/*.go') }}
          ${{ runner.os }}-build-
    - name: release
      run: goreleaser release --clean --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  container:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master'
      && startsWith(github.ref, 'refs/tags/')
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: pre-fetch taskfile
      run: task --download --yes
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
    - name: cache buildx
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${{ runner.temp }}/.buildx-cache
        # yamllint disable-line rule:line-length
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', '.dockerignore') }}
        # yamllint disable rule:line-length
        restore-keys: |
          ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', '.dockerignore') }}
          ${{ runner.os }}-buildx-
        # yamllint enable rule:line-length
    # fix to prevent ever-growing caches
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: push image
      run: >-
        task docker:push --
        --cache-to type=local,mode=max,dest=${{ runner.temp }}/.buildx-cache-new
        --cache-from type=local,src=${{ runner.temp }}/.buildx-cache
    # fix to prevent ever-growing caches
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf ${{ runner.temp }}/.buildx-cache
        mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
    - name: update DockerHub description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASSWORD }}
        description: true
