name: Release
# yamllint disable-line rule:truthy
on:
  push:
    tags:
    - '*'
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    if: >-
      github.ref == 'refs/heads/master'
      && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: binaries
      run: make dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
    - name: login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: container
      run: make image-push
    - name: update DockerHub description
      uses: meeDamian/sync-readme@v1.0.6
      with:
        pass: ${{ secrets.DOCKER_PASSWORD }}
        description: true
