name: Security

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master
    paths:
    - .dockerignore
    - .env
    - .envrc
    - .github/workflows/security.yml
    - .golangci.yaml
    - .task/*.yaml
    - '**.go'
    - Dockerfile
    - go.mod
    - go.sum
    - shell.nix
    - Taskfile.yaml
  pull_request:
    branches:
    - master
    paths:
    - .github/workflows/codeql.yml
    - .golangci.yaml
    - Dockerfile
    - .dockerignore
    - go.mod
    - go.sum
    - '**.go'
  schedule:
  - cron: '0 9 * * 1'

env:
  GOLANG_VERSION: "1.22"
  GOLANG_FLAGS: -race -mod=readonly
  GRYPE_DB_CACHE_TEMP_PATH: .cache/grype/db/

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.1.0
      with:
        install-nix: true
        cache-store: true
    - name: initialize
      uses: github/codeql-action/init@v3
      with:
        languages: go
    - name: build
      run: task build
    - name: analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:go"
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.1.0
      with:
        install-nix: true
        cache-store: true
    - name: set up docker buildx
      uses: docker/setup-buildx-action@v3
    - name: cache build
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${{ runner.temp }}/.buildx-cache
        # yamllint disable-line rule:line-length
        key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', '.dockerignore') }}
        # yamllint disable rule:line-length
        restore-keys: |
          ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', '.dockerignore') }}
          ${{ runner.os }}-buildx-
        # yamllint enable rule:line-length
    - name: build image
      run: >-
        task docker:build --
        --cache-to type=local,mode=max,dest=${{ runner.temp }}/.buildx-cache-new
        --cache-from type=local,src=${{ runner.temp }}/.buildx-cache
    # fix to prevent ever-growing caches
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: move build cache
      run: |
        rm -rf ${{ runner.temp }}/.buildx-cache
        mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
    - name: cache grype
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${{ runner.temp }}/${{ env.GRYPE_DB_CACHE_TEMP_PATH }}
        key: ${{ runner.os }}-grype-${{ hashFiles('.grype.yaml') }}
        restore-keys: |
          ${{ runner.os }}-grype-${{ hashFiles('.grype.yaml') }}
          ${{ runner.os }}-grype-
    - name: update db
      run: grype db update || grype db delete && grype db update
    - name: scan
      run: grype -o sarif --fail-on critical ${{ github.repository }}:edge > grype.sarif
    - name: report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: grype.sarif
