name: Security

# yamllint disable-line rule:truthy
on:
  push:
    branches:
    - master
    - user/*/trunk
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
    - media.db.sql
  pull_request:
    branches:
    - master
    - user/*/trunk
    paths-ignore:
    - .direnv
    - .helix
    - .meta
    - docs
    - "*.md"
    - .codecov.yml
    - media.db.sql
  schedule:
  - cron: '0 9 * * 1'

env:
  GRYPE_DB_CACHE_TEMP_PATH: .cache/grype/db/

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: direnv nix
      uses: JRMurr/direnv-nix-action@v4.2.0
      with:
        install-nix: true
        cache-store: true
    - name: cache grype
      uses: pat-s/always-upload-cache@v3
      with:
        path: ${{ runner.temp }}/${{ env.GRYPE_DB_CACHE_TEMP_PATH }}
        key: ${{ runner.os }}-grype-${{ hashFiles('.grype.yaml') }}
        restore-keys: |
          ${{ runner.os }}-grype-${{ hashFiles('.grype.yaml') }}
          ${{ runner.os }}-grype-
    - name: scan
      run: make sast
      timeout-minutes: 5
    - name: report
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: sast.sarif
